[2025-02-06T08:18:39.247+0000] {processor.py:157} INFO - Started process (PID=36361) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:18:39.248+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:18:39.248+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:18:39.248+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:18:39.253+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:18:39.250+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:18:39.253+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:18:39.266+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.021 seconds
[2025-02-06T08:19:09.851+0000] {processor.py:157} INFO - Started process (PID=36662) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:19:09.852+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:19:09.852+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:19:09.852+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:19:09.855+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:19:09.854+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:19:09.855+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:19:09.868+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.019 seconds
[2025-02-06T08:19:40.342+0000] {processor.py:157} INFO - Started process (PID=36971) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:19:40.343+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:19:40.343+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:19:40.343+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:19:40.347+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:19:40.346+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:19:40.348+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:19:40.360+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.020 seconds
[2025-02-06T08:20:10.744+0000] {processor.py:157} INFO - Started process (PID=38873) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:20:10.745+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:20:10.746+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:20:10.746+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:20:10.749+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:20:10.747+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:20:10.749+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:20:10.761+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.020 seconds
[2025-02-06T08:20:41.502+0000] {processor.py:157} INFO - Started process (PID=39084) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:20:41.502+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:20:41.503+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:20:41.502+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:20:41.506+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:20:41.504+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:20:41.506+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:20:41.518+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.019 seconds
[2025-02-06T08:21:11.700+0000] {processor.py:157} INFO - Started process (PID=39289) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:21:11.701+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:21:11.701+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:21:11.701+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:21:11.704+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:21:11.703+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:21:11.704+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:21:11.717+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.019 seconds
[2025-02-06T08:21:42.552+0000] {processor.py:157} INFO - Started process (PID=39840) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:21:42.553+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:21:42.553+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:21:42.553+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:21:42.556+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:21:42.555+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:21:42.557+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:21:42.569+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.019 seconds
[2025-02-06T08:22:13.542+0000] {processor.py:157} INFO - Started process (PID=40685) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:22:13.543+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:22:13.543+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:22:13.543+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:22:13.547+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:22:13.545+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:22:13.547+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:22:13.559+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.019 seconds
[2025-02-06T08:22:43.940+0000] {processor.py:157} INFO - Started process (PID=40978) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:22:43.941+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:22:43.942+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:22:43.942+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:22:43.945+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:22:43.944+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:22:43.945+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:22:43.957+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.019 seconds
[2025-02-06T08:23:14.336+0000] {processor.py:157} INFO - Started process (PID=41798) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:23:14.337+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:23:14.338+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:23:14.338+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:23:14.342+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:23:14.340+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:23:14.342+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:23:14.354+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.020 seconds
[2025-02-06T08:23:44.655+0000] {processor.py:157} INFO - Started process (PID=42186) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:23:44.656+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:23:44.657+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:23:44.656+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:23:44.660+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:23:44.658+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:23:44.660+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:23:44.672+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.020 seconds
[2025-02-06T08:24:01.258+0000] {processor.py:157} INFO - Started process (PID=42314) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:01.259+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:24:01.259+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:01.259+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:01.263+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:01.262+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:24:01.263+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:01.276+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.020 seconds
[2025-02-06T08:24:03.524+0000] {processor.py:157} INFO - Started process (PID=42330) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:03.524+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:24:03.525+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:03.525+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:03.528+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:03.527+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:24:03.529+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:03.541+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.020 seconds
[2025-02-06T08:24:06.290+0000] {processor.py:157} INFO - Started process (PID=42346) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:06.291+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:24:06.291+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:06.291+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:06.295+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:06.293+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:24:06.295+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:06.308+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.020 seconds
[2025-02-06T08:24:12.345+0000] {processor.py:157} INFO - Started process (PID=42387) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:12.346+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:24:12.347+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:12.346+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:12.350+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:12.349+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:24:12.351+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:12.362+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.019 seconds
[2025-02-06T08:24:30.310+0000] {processor.py:157} INFO - Started process (PID=42521) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:30.310+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:24:30.311+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:30.311+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:30.314+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:30.313+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:24:30.314+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:30.327+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.019 seconds
[2025-02-06T08:24:34.034+0000] {processor.py:157} INFO - Started process (PID=42546) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:34.034+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:24:34.035+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:34.035+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:34.039+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:34.037+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:24:34.039+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:34.052+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.021 seconds
[2025-02-06T08:24:37.611+0000] {processor.py:157} INFO - Started process (PID=42565) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:37.611+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:24:37.612+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:37.612+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:37.616+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:37.614+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:24:37.616+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:37.628+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.019 seconds
[2025-02-06T08:24:41.612+0000] {processor.py:157} INFO - Started process (PID=42598) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:41.612+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:24:41.613+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:41.613+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:41.616+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:41.615+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:24:41.616+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:41.628+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.019 seconds
[2025-02-06T08:24:45.611+0000] {processor.py:157} INFO - Started process (PID=42625) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:45.612+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:24:45.613+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:45.612+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:45.616+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:24:45.615+0000] {dagbag.py:350} ERROR - Failed to import: /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py", line 5, in <module>
    with DAG(
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 452, in __init__
    validate_key(dag_id)
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 55, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'extract S&P data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-02-06T08:24:45.616+0000] {processor.py:838} WARNING - No viable dags retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:24:45.628+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.018 seconds
[2025-02-06T08:27:06.989+0000] {processor.py:157} INFO - Started process (PID=44450) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:27:06.989+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:27:06.990+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:27:06.990+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:27:06.998+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_SnP']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:27:07.152+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:27:07.152+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:extract_SnP
[2025-02-06T08:27:07.160+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:27:07.160+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:extract_SnP
[2025-02-06T08:27:07.166+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:27:07.166+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:extract_SnP
[2025-02-06T08:27:07.174+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:27:07.174+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-02-06T08:27:07.181+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:27:07.180+0000] {dag.py:2763} INFO - Creating ORM DAG for extract_SnP
[2025-02-06T08:27:07.186+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:27:07.186+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_SnP to None, run_after=None
[2025-02-06T08:27:07.202+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.216 seconds
[2025-02-06T08:27:37.336+0000] {processor.py:157} INFO - Started process (PID=44801) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:27:37.336+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:27:37.337+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:27:37.337+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:27:37.344+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_SnP']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:27:37.360+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:27:37.360+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-02-06T08:27:37.453+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:27:37.453+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_SnP to None, run_after=None
[2025-02-06T08:27:37.467+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.133 seconds
[2025-02-06T08:28:08.127+0000] {processor.py:157} INFO - Started process (PID=45690) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:28:08.128+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:28:08.129+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:28:08.128+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:28:08.136+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_SnP']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:28:08.151+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:28:08.151+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-02-06T08:28:08.243+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:28:08.243+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_SnP to None, run_after=None
[2025-02-06T08:28:08.256+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.131 seconds
[2025-02-06T08:28:38.366+0000] {processor.py:157} INFO - Started process (PID=46015) to work on /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:28:38.367+0000] {processor.py:826} INFO - Processing file /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py for tasks to queue
[2025-02-06T08:28:38.367+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:28:38.367+0000] {dagbag.py:541} INFO - Filling up the DagBag from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:28:38.375+0000] {processor.py:836} INFO - DAG(s) dict_keys(['extract_SnP']) retrieved from /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py
[2025-02-06T08:28:38.391+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:28:38.391+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-02-06T08:28:38.487+0000] {logging_mixin.py:150} INFO - [2025-02-06T08:28:38.487+0000] {dag.py:3504} INFO - Setting next_dagrun for extract_SnP to None, run_after=None
[2025-02-06T08:28:38.501+0000] {processor.py:179} INFO - Processing /workspaces/hands-on-introduction-data-engineering-4395021/airflow/dags/extract-sandp-dag.py took 0.137 seconds
